// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination=./mocks/task_mock.go -source=task.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "go-tasks-api/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskConnector is a mock of TaskConnector interface.
type MockTaskConnector struct {
	ctrl     *gomock.Controller
	recorder *MockTaskConnectorMockRecorder
	isgomock struct{}
}

// MockTaskConnectorMockRecorder is the mock recorder for MockTaskConnector.
type MockTaskConnectorMockRecorder struct {
	mock *MockTaskConnector
}

// NewMockTaskConnector creates a new mock instance.
func NewMockTaskConnector(ctrl *gomock.Controller) *MockTaskConnector {
	mock := &MockTaskConnector{ctrl: ctrl}
	mock.recorder = &MockTaskConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskConnector) EXPECT() *MockTaskConnectorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskConnector) Create(ctx context.Context, a model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskConnectorMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskConnector)(nil).Create), ctx, a)
}

// Delete mocks base method.
func (m *MockTaskConnector) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskConnectorMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskConnector)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockTaskConnector) Get(ctx context.Context, id string) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskConnectorMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskConnector)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTaskConnector) List(ctx context.Context) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskConnectorMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskConnector)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockTaskConnector) Update(ctx context.Context, task model.Task) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, task)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskConnectorMockRecorder) Update(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskConnector)(nil).Update), ctx, task)
}
